# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  dummy-job:
    working_directory: ~/repo
    docker:
    - image: circleci/python:3.7.1

    steps:
    - checkout
    - run:
        name: dummy-step
        command: |
          echo "This is just a place holder, maybe one day I will do something more useful..."

workflows:
  version: 2
  build-and-deploy:
    jobs:
    - dummy-job
